config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "homes#top"
  get "home/about" => "homes#about"
  get "searches" => "searches#search"

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :books do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.looks(word, search)
    if search == "perfect_match"
      Book.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      Book.where("title LIKE?", "#{word}%")
    elsif search == "backword_match"
      Book.where("title LIKE?", "%#{word}")
    elsif search == "partial_match"
      Book.where("title LIKE?", "%#{word}%")
    else
      Book.all
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :following, class_name: "User"
    belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}
  attachment :profile_image
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    passive_relationships.where(following_id: user.id).exists?
  end

  def self.looks(word, search)
    if search == "perfect_match"
      User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      User.where("name LIKE?", "#{word}%")
    elsif search == "backword_match"
      User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      User.where("name LIKE?", "%#{word}%")
    else
      User.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @newbook = Book.new
    @user = @book.user
    @comments = @book.comments
    @comment = Comment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.comments.new(comment_params)
    @comment.book_id = @book.id
    @comment.save
    render :index
    #redirect_back(fallback_location: root_path)

  end

  def destroy
    @book = Book.find(params[:book_id])
    @comment = Comment.find_by(id: params[:id], book_id: @book.id)
    @comment.destroy
    render :index
    #redirect_back(fallback_location: root_path)
  end

  private
    def comment_params
      params.require(:comment).permit(:comment)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @favorite = Favorite.new(user_id: current_user.id, book_id: @book.id)
    @favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = Favorite.find_by(user_id: current_user.id, book_id: @book.id)
    @favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:word], params[:search])
    else
      @books = Book.looks(params[:word], params[:search])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def follows
    @user = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end
  private
    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error.erb
<% if model.errors.any? %>
  <div class="error">
    <% if model.errors.count == 1 %>
      <h3><%= model.errors.count %> error prohibited this obj from being saved:</h3>
    <% else %>
      <h3><%= model.errors.count %>errors prohibited this obj from being saved:</h3>
    <% end %>

    <% model.errors.full_messages.each do |message| %>
      <li>
        <%= message %>
      </li>
    <% end %>
  </div>
<% end %>

app/views/books/_form.erb
<h2 class="mt-3">New book</h2>
  <%= form_with model: book, local: true do |f| %>
    <div class="form-group">
      <label>Title</label>
      <%= f.text_field :title, class:"form-control" %>
    </div>
    <div class="form-group">
      <label>Opinion</label>
      <%= f.text_area :body, class:"form-control" %>
    </div>
    <%= f.submit "Create Book", class:"btn btn-success" %>
  <% end %>

app/views/books/edit.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= render "books/error", model: @book %>
      <%= form_with model: @book, local: true do |f| %>
        <div class="form-group">
          <label>Title</label>
          <%= f.text_field :title, class:"form-control" %>
        </div>
        <div class="form-group">
          <label>Opinion</label>
          <%= f.text_area :body, class:"form-control" %>
        </div>
        <%= f.submit "Update Book", class:"btn btn-success" %>
      <% end %>
      <div class="mt-3">
        <%= link_to "Show", book_path(@book) %>
         |
        <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container mt-3">
  <%= render "books/error", model: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @user %>
      <%= render "books/form", book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, fallback:"no_image.jpg", size:"40x40"  %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book) %>
              </td>
              <td><%= book.body %></td>
              <td class="favorite_btn_<%= book.id %>">
                <%= render "favorites/favorite", book: book %>
              </td>
              <td>
               コメント数：<%= book.comments.count %>
            　</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/books/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @user %>
      <%= render "books/form", book: @newbook %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
                <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "40x40" %><br>
                <%= @user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book) do %>
                <%= @book.title %>
              <% end %>
            </td>
            <td>
              <%= @book.body %>
            </td>
            <td class="favorite_btn_<%= @book.id %>">
              <%= render "favorites/favorite", book: @book %>
            </td>
            <td>
              コメント数：<%= @comments.count %>
            </td>
            <% if @user == current_user %>
              <td>
                <%= link_to "Edit", edit_book_path, class:"btn btn-sm btn-success"  %>
              </td>
              <td>
                <%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-sm btn-danger"  %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <table id="comments_area">
        <%= render "comments/index", comments: @comments %>
      </table>

      <%= form_with model: [@book, @comment] do |f| %>
        <div class="form-group">
          <%= f.text_area :comment, rows:5, class:"w-100" %>
        </div>
        <%= f.submit "送信" %>
      <% end %>


    </div>
  </div>
</div>

app/views/comments/_index.html.erb
<tbody>
  <% comments.each do |comment| %>
    <tr>
      <td>
        <%=link_to user_path(comment.user) do %>
          <%= attachment_image_tag comment.user, :profile_image, fallback: "no_image.jpg", size: "40x40" %><br>
          <%= comment.user.name %>
        <% end %>
      </td>
      <td><%= comment.comment %></td>
      <% if comment.user == current_user %>
        <td>
          <%= link_to "Destroy", book_comment_path(comment.book, comment), method: :delete, remote: true, class:"btn btn-sm btn-danger" %>
        </td>
      <% end %>
    </tr>
  <% end %>
</tbody>

app/views/comments/index.js.erb
$('#comments_area').html('<%= j(render "index", comments: @book.comments) %>');
$('textarea').val('');

app/views/favorites/_favorite.html.erb
  <% if book.favorited_by?(current_user) %>
    <%= link_to  book_favorites_path(book), method: :delete, remote: true do %>
      <i class="fas fa-heart unlike-btn"><%= book.favorites.count %></i>
    <% end %>
　<% else %>
    <%= link_to  book_favorites_path(book), method: :post, remote: true do %>
      <i class="fas fa-heart like-btn" ><%= book.favorites.count %></i>
    <% end %>
　<% end %>

app/views/favorites/create.js.erb
$('.favorite_btn_<%= @book.id %>').html('<%= j(render "favorites/favorite", book: @book) %>');

app/views/favorites/destroy.js.erb
$('.favorite_btn_<%= @book.id %>').html('<%= j(render "favorites/favorite", book: @book) %>');

app/views/homes/about.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="mx-auto">
      <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container mt-3">
 <div class="row">
    <div class=" col-11 col-sm-10 col-lg-8 col-xl-6 mx-auto">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class:"btn btn-sm btn-info btn-block mb-3" %>
        </div>
        <div class="row">
          <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-sm btn-success btn-block" %>
        </div>
      </div>
    </div>
 </div>
</div>

app/views/searches/_search_form.html.erb
<% if user_signed_in? %>
  <%= form_with url: searches_path, local: true, method: :get do |f| %>
    <%= f.text_field :word %>
    <%= f.select :range, options_for_select([["User"], ["Book"]]) %>
    <%= f.select :search, options_for_select([["完全一致", "perfect_match"], ["前方一致", "forward_match"], ["後方一致", "backword_match"], ["部分一致", "partial_match"]]) %>
    <%= f.submit "検索" %>
  <% end %>
<% end %>

app/views/searches/search.html.erb
<% if @range == "User" %>
  <% if @users.any? %>
    <h2>Users search for "<%= params[:word] %>"</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "40x40" %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
        <% end %>
      </tbody>
　　</table>
  <% else %>
    <h2>Users search for "<%= params[:word] %>"</h2>
    該当のユーザーが見つかりませんでした
  <% end %>
<% else %>
  <% if @books.any? %>
    <h2>Books search for "<%= params[:word] %>"</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td><%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size: "40x40" %></td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
      </tbody>
　　</table>
  <% else %>
    <h2>Books search for "<%= params[:word] %>"</h2>
    該当の書籍が見つかりませんでした
  <% end %>
<% end %>

app/views/users/_follow.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "40x40" %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.active_relationships.count %></td>
        <td>フォロワー数：<%= user.passive_relationships.count %></td>
        <td><%= link_to "Show", user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.erb
  <h2>User info</h2>
    <%= attachment_image_tag user, :profile_image, fallback:"no_image.jpg", size:"100x100" %>
    <table class="table">
      <tbody>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
        <tr>
          <th>follows</th>
          <th>
            <%= link_to follows_user_path(user) do %>
              <%= user.active_relationships.count %>
            <% end %>
          </th>
        </tr>
        <tr>
          <th>followers</th>
          <th>
            <%= link_to followers_user_path(user) do %>
              <%= user.passive_relationships.count %>
            <% end %>
          </th>
        </tr>
      </tbody>
    </table>
    <% if user == current_user %>
      <div class="row">
        <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
    <% else %>
      <% if user.followed_by?(current_user) %>
        <%= link_to "フォロー外す", user_relationships_path(user), method: :delete, class: "btn btn-primary mt-3" %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user), method: :post, class: "btn btn-success mt-3" %>
      <% end %>
    <% end %>

app/views/users/edit.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= render "books/error", model: @user %>
      <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
          <label>Name</label>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
          <label>Image</label>
          <%= f.attachment_field :profile_image, class:"form-control-file" %>
        </div>
        <div class="form-group">
          <label>Introduction</label>
          <%= f.text_area :introduction, class:"form-control" %>
        </div>
        <%= f.submit "Update User", class:"btn btn-secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
<% if @users.any? %>
  <%= render "users/follow", users: @users %>
<% else %>
  ユーザーはいません
<% end %>

app/views/users/follows.html.erb
<h2>Follow Users</h2>
<% if @users.any? %>
  <%= render "users/follow", users: @users %>
<% else %>
  ユーザーはいません
<% end %>

app/views/users/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @user %>
      <%= render "books/form", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "40x40" %>
              </td>
              <td><%= user.name %></td>
              <td>フォロー数：<%= user.active_relationships.count %></td>
              <td>フォロワー数：<%= user.passive_relationships.count %></td>
              <td>
                <% if user != current_user %>
                  <% if user.followed_by?(current_user) %>
                    <%= link_to "フォロー外す", user_relationships_path(user), method: :delete %>
                  <% else %>
                    <%= link_to "フォローする", user_relationships_path(user), method: :post %>
                  <% end %>
                <% end %>
              </td>
              <td>
                <%= link_to "Show", user_path(user) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @user %>
      <%= render "books/form", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(@user) do %>
                  <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "40x40" %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book) %>
              </td>
              <td><%= book.body %></td>
              <td>
              コメント数：<%= book.comments.count %>
            　</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>